### ISSUE TITLE
DateString not exposed as TypeScript type - prevents use in Loopback 4

### ISSUE THREAD

**Issue by benjamincburns** [loopbackio/loopback-datasource-juggler#1885]
## Steps to reproduce

1. Try adding a property of type `DateString` to a TypeScript model in loopback 4.

## Current Behavior

Can't import type `DateString` because it's implemented in pure JS and not exposed by any type declaration file.

## Expected Behavior

I'd be able to do something like `import { DateString } from "loopback-datasource-juggler"` in TypeScript code.

It would appear that this is possible, as `DateString` is listed on the [Loopback types page](https://loopback.io/doc/en/lb4/LoopBack-types.html) in the Loopback 4 docs.

## Link to reproduction sandbox

There's nothing to sandbox because the code won't even compile.

**Comment by benjamincburns** [comment]
@achrinza similar to my comment on another issue - if you agree that this bug is valid, perhaps it should be ignored by stalebot.

**Comment by achrinza** [comment]
Apologies for missing the issue; This would be solved with the addition of type definitions to Juggler.

Currently we don't have the resources to implement the typedefs and tests right now but are open to community contributions.

As for stalebot, it acts as a gentle reminder that the issue is still open; So if the issue is still valid, we'll remove the stale tag :)

**Comment by achrinza** [comment]
Currently being worked on by: https://github.com/loopbackio/loopback-datasource-juggler/pull/1902

**Comment by benjamincburns** [comment]
Closing, as #1902 was merged
